/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary:                   '#003f87',
        'primary-container':       '#0056b3',
        'on-primary':              '#ffffff',
        'on-primary-container':    '#bbd0ff',
        'primary-fixed':           '#d7e2ff',
        'primary-fixed-dim':       '#acc7ff',
        'on-primary-fixed':        '#001a40',
        'on-primary-fixed-variant':'#004491',
        secondary:                 '#585f68',
        'secondary-container':     '#dde3ee',
        'on-secondary':            '#ffffff',
        'on-secondary-container':  '#5e656e',
        'secondary-fixed':         '#dde3ee',
        'on-secondary-fixed':      '#161c24',
        tertiary:                  '#722b00',
        'tertiary-container':      '#983c00',
        'on-tertiary':             '#ffffff',
        'on-tertiary-container':   '#ffc2a7',
        'tertiary-fixed':          '#ffdbcc',
        'tertiary-fixed-dim':      '#ffb694',
        'on-tertiary-fixed':       '#351000',
        'on-tertiary-fixed-variant':'#7b2f00',
        error:                     '#ba1a1a',
        'error-container':         '#ffdad6',
        'on-error':                '#ffffff',
        'on-error-container':      '#93000a',
        surface:                   '#f6faff',
        background:                '#f6faff',
        'surface-variant':         '#dbe4ed',
        'surface-dim':             '#d2dbe4',
        'surface-bright':          '#f6faff',
        'surface-tint':            '#115cb9',
        'surface-container-lowest':'#ffffff',
        'surface-container-low':   '#ecf5fe',
        'surface-container':       '#e6eff8',
        'surface-container-high':  '#e0e9f2',
        'surface-container-highest':'#dbe4ed',
        'on-surface':              '#141d23',
        'on-surface-variant':      '#424752',
        'on-background':           '#141d23',
        outline:                   '#727784',
        'outline-variant':         '#c2c6d4',
        'inverse-surface':         '#293138',
        'inverse-on-surface':      '#e9f2fb',
        'inverse-primary':         '#acc7ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'xs':             '4px',
        'sm':             '12px',
        'md':             '16px',
        'lg':             '24px',
        'xl':             '40px',
        'base':           '8px',
        'gutter':         '24px',
        'margin-mobile':  '16px',
        'margin-desktop': '32px',
      },
      fontFamily: { sans: ['Inter', 'sans-serif'] },
      fontSize: {
        'label-sm':  ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md':  ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-sm':   ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md':   ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg':   ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'title-lg':  ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md':['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg':['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
